# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Perl6-Subs
version:      0.05
version_from: lib/Perl6/Subs.pm
installdirs:  site
requires:
    Filter::Simple:                0.70
    Parse::RecDescent:             1.91
    Test::More:                    0
    Text::Balanced:                1.90

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
